# Generated by Django 3.2.4 on 2021-06-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_user_info_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='about',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='sex',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
