# Generated by Django 3.2.4 on 2021-06-19 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210619_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='language_to_learn',
            new_name='desired',
        ),
        migrations.RenameField(
            model_name='user_info',
            old_name='native_language',
            new_name='native',
        ),
    ]
