# Generated by Django 3.2.4 on 2021-06-20 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
