# Generated by Django 3.2.4 on 2021-06-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='country',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='sex',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
