# Generated by Django 3.2.4 on 2021-06-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210629_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessages',
            name='sent_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
