# Generated by Django 3.2.4 on 2021-06-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_chatmessages_sent_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_name',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
