# Generated by Django 3.2.4 on 2021-07-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_chatroom_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechatroom',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
