# Generated by Django 3.2.4 on 2021-07-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_privatechatroom_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
