# Generated by Django 3.2.4 on 2021-07-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='picture',
            field=models.ImageField(upload_to='avatar/'),
        ),
    ]
