# Generated by Django 3.2.4 on 2021-07-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_alter_profilepicture_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
