# Generated by Django 3.2.4 on 2021-07-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_alter_chatinfo_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isonline',
            name='last_time_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
