# Generated by Django 3.2.4 on 2021-07-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_alter_isonline_last_time_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessages',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
